name: Waka Readme

on:
  schedule:
    # Se ejecuta a las 00:15 y 12:15 cada día (dos veces al día)
    - cron: '15 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Ajustes recomendados para que se vea bien:
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "False"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE_PER_REPO: "True"